apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: logseq
data:
  logseq-nginx-conf: |
    server {
    listen  443   ssl;
    ssl_certificate /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;
    server_name  localhost;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }