apiVersion: v1
kind: Service
metadata:
  labels:
    app: logseq
  name: logseq
  namespace: logseq
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: logseq
status:
  loadBalancer: {}
